compressionLevel: mixed

enableGlobalCache: false

plugins:
  - path: .yarn/plugins/plugin-list.cjs
    spec: "https://github.com/arendjr/yarn-plugin-list/releases/latest/download/yarn-plugin-list.js"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
